go:
    version: 1.23
repository:
    path: github.com/barmettlerl/jiralert
build:
    binaries:
        - name: jiralert
          path: cmd/jiralert
    flags: -a -tags netgo
crossbuild:
    platforms:
        - linux/amd64
