name: build-docker

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set timestamp
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build .\
          --tag ghcr.io/${{ github.repository_owner }}/jiralert:${{ env.IMAGE_TAG }} \
          --tag ghcr.io/${{ github.repository_owner }}/jiralert:latest

    - name: Push the Docker image with timestamp tag
      run: docker push ghcr.io/${{ github.repository_owner }}/jiralert:${{ env.IMAGE_TAG }}

    - name: Push the Docker image with latest tag
      run: docker push ghcr.io/${{ github.repository_owner }}/jiralert:latest
